package shadcnscalajs.blocks.dashboard01

/** Sample rows from shadcn-svelte `blocks/dashboard-01/data.ts`. */
object Data:

  final case class Row(
      id: Int,
      header: String,
      sectionType: String,
      status: String,
      target: String,
      limit: String,
      reviewer: String
  )

  val rows: List[Row] = List(
    Row(1, "Cover page", "Cover page", "In Process", "18", "5", "Eddie Lake"),
    Row(2, "Table of contents", "Table of contents", "Done", "29", "24", "Eddie Lake"),
    Row(3, "Executive summary", "Narrative", "Done", "10", "13", "Eddie Lake"),
    Row(4, "Technical approach", "Narrative", "Done", "27", "23", "Jamik Tashpulatov"),
    Row(5, "Design", "Narrative", "In Process", "2", "16", "Jamik Tashpulatov"),
    Row(6, "Capabilities", "Narrative", "In Process", "20", "8", "Jamik Tashpulatov"),
    Row(7, "Integration with existing systems", "Narrative", "In Process", "19", "21", "Jamik Tashpulatov"),
    Row(8, "Innovation and Advantages", "Narrative", "Done", "25", "26", "Assign reviewer"),
    Row(9, "Overview of EMR's Innovative Solutions", "Technical content", "Done", "7", "23", "Assign reviewer"),
    Row(10, "Advanced Algorithms and Machine Learning", "Narrative", "Done", "30", "28", "Assign reviewer"),
    Row(11, "Adaptive Communication Protocols", "Narrative", "Done", "9", "31", "Assign reviewer"),
    Row(12, "Advantages Over Current Technologies", "Narrative", "Done", "12", "0", "Assign reviewer"),
    Row(13, "Past Performance", "Narrative", "Done", "22", "33", "Assign reviewer"),
    Row(14, "Customer Feedback and Satisfaction Levels", "Narrative", "Done", "15", "34", "Assign reviewer"),
    Row(15, "Implementation Challenges and Solutions", "Narrative", "Done", "3", "35", "Assign reviewer"),
    Row(16, "Security Measures and Data Protection Policies", "Narrative", "In Process", "6", "36", "Assign reviewer"),
    Row(17, "Scalability and Future Proofing", "Narrative", "Done", "4", "37", "Assign reviewer"),
    Row(18, "Cost-Benefit Analysis", "Plain language", "Done", "14", "38", "Assign reviewer"),
    Row(19, "User Training and Onboarding Experience", "Narrative", "Done", "17", "39", "Assign reviewer"),
    Row(20, "Future Development Roadmap", "Narrative", "Done", "11", "40", "Assign reviewer"),
    Row(21, "System Architecture Overview", "Technical content", "In Process", "24", "18", "Maya Johnson"),
    Row(22, "Risk Management Plan", "Narrative", "Done", "15", "22", "Carlos Rodriguez"),
    Row(23, "Compliance Documentation", "Legal", "In Process", "31", "27", "Sarah Chen"),
    Row(24, "API Documentation", "Technical content", "Done", "8", "12", "Raj Patel"),
    Row(25, "User Interface Mockups", "Visual", "In Process", "19", "25", "Leila Ahmadi"),
    Row(26, "Database Schema", "Technical content", "Done", "22", "20", "Thomas Wilson"),
    Row(27, "Testing Methodology", "Technical content", "In Process", "17", "14", "Assign reviewer"),
    Row(28, "Deployment Strategy", "Narrative", "Done", "26", "30", "Eddie Lake"),
    Row(29, "Budget Breakdown", "Financial", "In Process", "13", "16", "Jamik Tashpulatov"),
    Row(30, "Market Analysis", "Research", "Done", "29", "32", "Sophia Martinez"),
    Row(31, "Competitor Comparison", "Research", "In Process", "21", "19", "Assign reviewer"),
    Row(32, "Maintenance Plan", "Technical content", "Done", "16", "23", "Alex Thompson"),
    Row(33, "User Personas", "Research", "In Process", "27", "24", "Nina Patel"),
    Row(34, "Accessibility Compliance", "Legal", "Done", "18", "21", "Assign reviewer"),
    Row(35, "Performance Metrics", "Technical content", "In Process", "23", "26", "David Kim"),
    Row(36, "Disaster Recovery Plan", "Technical content", "Done", "14", "17", "Jamik Tashpulatov"),
    Row(37, "Third-party Integrations", "Technical content", "In Process", "25", "28", "Eddie Lake"),
    Row(38, "User Feedback Summary", "Research", "Done", "20", "15", "Assign reviewer"),
    Row(39, "Localization Strategy", "Narrative", "In Process", "12", "19", "Maria Garcia"),
    Row(40, "Mobile Compatibility", "Technical content", "Done", "28", "31", "James Wilson"),
    Row(41, "Data Migration Plan", "Technical content", "In Process", "19", "22", "Assign reviewer"),
    Row(42, "Quality Assurance Protocols", "Technical content", "Done", "30", "33", "Priya Singh"),
    Row(43, "Stakeholder Analysis", "Research", "In Process", "11", "14", "Eddie Lake"),
    Row(44, "Environmental Impact Assessment", "Research", "Done", "24", "27", "Assign reviewer"),
    Row(45, "Intellectual Property Rights", "Legal", "In Process", "17", "20", "Sarah Johnson"),
    Row(46, "Customer Support Framework", "Narrative", "Done", "22", "25", "Jamik Tashpulatov"),
    Row(47, "Version Control Strategy", "Technical content", "In Process", "15", "18", "Assign reviewer"),
    Row(48, "Continuous Integration Pipeline", "Technical content", "Done", "26", "29", "Michael Chen"),
    Row(49, "Regulatory Compliance", "Legal", "In Process", "13", "16", "Assign reviewer"),
    Row(50, "User Authentication System", "Technical content", "Done", "28", "31", "Eddie Lake"),
    Row(51, "Data Analytics Framework", "Technical content", "In Process", "21", "24", "Jamik Tashpulatov"),
    Row(52, "Cloud Infrastructure", "Technical content", "Done", "16", "19", "Assign reviewer"),
    Row(53, "Network Security Measures", "Technical content", "In Process", "29", "32", "Lisa Wong"),
    Row(54, "Project Timeline", "Planning", "Done", "14", "17", "Eddie Lake"),
    Row(55, "Resource Allocation", "Planning", "In Process", "27", "30", "Assign reviewer"),
    Row(56, "Team Structure and Roles", "Planning", "Done", "20", "23", "Jamik Tashpulatov"),
    Row(57, "Communication Protocols", "Planning", "In Process", "15", "18", "Assign reviewer"),
    Row(58, "Success Metrics", "Planning", "Done", "30", "33", "Eddie Lake"),
    Row(59, "Internationalization Support", "Technical content", "In Process", "23", "26", "Jamik Tashpulatov"),
    Row(60, "Backup and Recovery Procedures", "Technical content", "Done", "18", "21", "Assign reviewer"),
    Row(61, "Monitoring and Alerting System", "Technical content", "In Process", "25", "28", "Daniel Park"),
    Row(62, "Code Review Guidelines", "Technical content", "Done", "12", "15", "Eddie Lake"),
    Row(63, "Documentation Standards", "Technical content", "In Process", "27", "30", "Jamik Tashpulatov"),
    Row(64, "Release Management Process", "Planning", "Done", "22", "25", "Assign reviewer"),
    Row(65, "Feature Prioritization Matrix", "Planning", "In Process", "19", "22", "Emma Davis"),
    Row(66, "Technical Debt Assessment", "Technical content", "Done", "24", "27", "Eddie Lake"),
    Row(67, "Capacity Planning", "Planning", "In Process", "21", "24", "Jamik Tashpulatov"),
    Row(68, "Service Level Agreements", "Legal", "Done", "26", "29", "Assign reviewer")
  )
